### ISSUE TITLE
(1) Add some sort of documentation reference to our team website

### ISSUE THREAD

**Issue by varzaman** [mozillascience/software-discovery-dashboard#11]

**Comment by lukecoy** [comment]
For our next sprint (or just whenever we make new issues from now on), we can always add more detail besides the title. 

In this case, I think that this was in response to our original bootstrap-y website essentially copy-pasting pictures of our diagrams and docs. 

Now that we have a new cleaner website, I think it would suffice to add a "docs" link to the top or something like that directly.

**Comment by amb8805** [comment]
Added Docs link
