### ISSUE TITLE
(6) Install and configure Jenkins

### ISSUE THREAD

**Issue by varzaman** [mozillascience/software-discovery-dashboard#12]

**Comment by lukecoy** [comment]
@Lettuceman44 , now that we have a functioning [branch](https://github.com/mozillascience/software-discovery-dashboard/tree/architecture), can you try making this an item on jenkins of this branch just to make sure we're golden? This is the [script I'd use](https://github.com/mozillascience/software-discovery-dashboard/blob/architecture/package.json#L6). We can collab on this

**Comment by varzaman** [comment]
Jenkins workflow set up, deploy workflow set up.

Github push -> Jenkins build -> On success use forever on node.js app.
