### ISSUE TITLE
Make Abby's bio on the team website

### ISSUE THREAD

**Issue by lukecoy** [mozillascience/software-discovery-dashboard#15]
@acabunoc deserves an awesome blurb.

Feel free to PR this line, which currently has Dons bio in place of yours:
https://github.com/mozillascience/software-discovery-dashboard/blob/gh-pages/index.html#L93

**Comment by abbycabs** [comment]
Amazing! Will look at this tomorrow 😀

**Comment by lukecoy** [comment]
@acabunoc got a nice bio, which was merged here: https://github.com/mozillascience/software-discovery-dashboard/commit/f3446c8fbaf43d4b9c70d13566f73bdb9ccb0ba6

closing issue
