### ISSUE TITLE
(2.5) Configure dev environment (back end)

### ISSUE THREAD

**Issue by varzaman** [mozillascience/software-discovery-dashboard#2]

**Comment by lukecoy** [comment]
This is in progress on this [branch](https://github.com/mozillascience/software-discovery-dashboard/tree/architecture). The dev environment currently supports features listed in this [commit](https://github.com/mozillascience/software-discovery-dashboard/commit/efd1be7c1ad78b62f1d8b5cc1360a4236dd2d7be).

TODO:
PR, get feedback, fix based on feedback
