### ISSUE TITLE
Create rest endpoint for figshare

### ISSUE THREAD

**Issue by varzaman** [mozillascience/software-discovery-dashboard#27]
Dependent on issue #26.

After authorization is complete, a simple rest endpoint that gets figshare repository metadata needs to be created. This will allow us to hook into their service, and allow us the ability to convert their metadata to the JSON-LD standard.

**Comment by lukecoy** [comment]
Authorization on figshare is complete, and an endpoint I've made is successfully fetching articles. I need to now focus on the JsonLd side of things, and converting incoming querys to figshares language.

**Comment by lukecoy** [comment]
Unit testing

**Comment by varzaman** [comment]
Finished
