### ISSUE TITLE
Prefer Travis CI for Open Source Projects?

### ISSUE THREAD

**Issue by lukecoy** [mozillascience/software-discovery-dashboard#44]
Travis CI (https://travis-ci.org/) 

"Easily sync your GitHub projects with Travis CI and you’ll be testing your code in minutes!"

Also, used by Mozilla. And free for open source projects. 

We should be preferring this to Jenkins which is super annoying to deal with. Thoughts @Lettuceman44

**Comment by varzaman** [comment]
We decided to use Travic CI over Jenkins for its simplicity and ease of use, especially with GitHub integration.

Closing this.
