### ISSUE TITLE
Javascript Style Guide:

### ISSUE THREAD

**Issue by lukecoy** [mozillascience/software-discovery-dashboard#45]
I'm using this on a personal project, and it's incredible:

https://github.com/airbnb/javascript

as you can tell by the amount of stars, it's actually a pretty popular style to follow, which is good for consistency. also, eslint supports it out of the box.

**Comment by mok4ry** [comment]
:+1: This is what we're going to use.

**Comment by mok4ry** [comment]
87c8b596aa1378c7588a13f0298dabd66efa0844
