### ISSUE TITLE
Gulp VS Npm Scripts

### ISSUE THREAD

**Issue by lukecoy** [mozillascience/software-discovery-dashboard#46]
I'm torn between getting rid of the whole bunch of dev dependencies we have under the gulp umbrella, and going for a more simple approach involving super simple Npm scripts. I've been working on a personal project that uses a lot of the same tech we use here, and it looks /soooo/ much cleaner. That, and I find that a lot of the times, certain tools just work really well on CLI and expect that VS using a node module. I can expand on some specific examples if anyone is curious. Thoughts?

**Comment by mok4ry** [comment]
As well as it went for a while, we need gulp in order to support React (browserify, moving to dist folder, etc.). So, gulp stays but in the background; `npm start` is still the best way to build and serve the project.
