### ISSUE TITLE
Results Page Hyperlinks 

### ISSUE THREAD

**Issue by amb8805** [mozillascience/software-discovery-dashboard#65]
There should only be one clickable hyperlink from the Results page per result.  Having 2 hyperlinks to the same location is misleading.  If you look at google the Title is clickable and the actual URL text is not clickable.  I believe it would be good practice to follow this approach and simply leave the URL as plain text and keep the hyperlink clickable.

**Comment by lukecoy** [comment]
:+1: adam can you handle this

**Comment by amb8805** [comment]
Yeah no problem.

**Comment by amb8805** [comment]
Fixed with the merge
