### ISSUE TITLE
Results page query bar shouldn't be editable

### ISSUE THREAD

**Issue by amb8805** [mozillascience/software-discovery-dashboard#75]

**Comment by mok4ry** [comment]
Maybe it should be, though. Right now we populate that bar with the query in a pseudo query language (`sources:DataCite keywords:Hello,World` etc.). The instinct when you see that is that you can modify it to modify the search.

Should we put a search button there and allow it, or make users go back to the home page to change their search?

**Comment by amb8805** [comment]
I think we should allow it, it would be more in line with google and wouldn't require us to have to go home and redo the search

**Comment by mok4ry** [comment]
Agreed. Let's make a new issue for that and then close this one.

**Comment by mok4ry** [comment]
New issue: #96
