### ISSUE TITLE
Results page says "No results found" if a repository query is taking a while

### ISSUE THREAD

**Issue by lukecoy** [mozillascience/software-discovery-dashboard#81]
It should indicate that it's loading results in some sort of way. It's only acceptable to say there's no results found if there /are/ no results found.

**Comment by mok4ry** [comment]
![screen shot 2016-04-21 at 2 41 18 pm](https://cloud.githubusercontent.com/assets/1236978/14720384/35443f74-07cf-11e6-8086-3e02af78bdcf.png)
cc @amb8805 @lukecoy @Lettuceman44
