### ISSUE TITLE
Logo and icons

### ISSUE THREAD

**Issue by mok4ry** [mozillascience/software-discovery-dashboard#86]
We should have some sort of logo that we can put on the home page and have as a favicon.

@lukecoy @amb8805 @Lettuceman44 Thoughts?

**Comment by amb8805** [comment]
Definitely Agree.  Maybe not the same as the favicon but definitely something that could be used to represent our product.  I think it's out of our realm of ability though.  Would it be possible to leverage a Graphic Designer either on our end, or someone from Mozilla?

**Comment by mok4ry** [comment]
Abby suggested that we do a first pass and run it by Ricardo.

**Comment by amb8805** [comment]
![opensd logo](https://cloud.githubusercontent.com/assets/2687437/14622148/f32c06c0-0595-11e6-861c-63000d71dd7d.png)

**Comment by amb8805** [comment]
![logoopensd](https://cloud.githubusercontent.com/assets/2687437/14893782/b57c5158-0d3e-11e6-8f45-307d59499353.png)

**Comment by amb8805** [comment]
Is this better? where should it go on the website

**Comment by mok4ry** [comment]
Icon introduced in PR #104 

Still need to add it as a favicon before we can close this issue out.

**Comment by mok4ry** [comment]
Favicons in PR #105 
Everything looks good to me
